// Swift port Copyright (C) 2026 Paul Tsochantaris
// SPDX-License-Identifier: GPL-2.0-or-later
//
// This file is part of a Swift port of reSIDfp, a SID emulator engine.
// Copyright 2011-2025 Leandro Nini <drfiemost@users.sourceforge.net>
// Copyright 2007-2010 Antti Lankila
// Copyright 2004 Dag Lem <resid@nimrod.no>
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// resample/Resampler.h, resample/ZeroOrderResampler.h, resample/SincResampler.h/.cpp and
// resample/TwoPassSincResampler.h.
//
// reSIDfp's Resampler is an abstract class; here the chip holds one resampler of each kind and its
// clocking loops are written once per kind, so nothing is dispatched per cycle. The FIR tables are
// built in double arithmetic in reSIDfp's operand order. The convolution is the plain integer loop
// reSIDfp gives clang (no intrinsics; integer sums are the same in any order, vectorised or not).
// SincResampler's ring buffer is zeroed when it is made: reSIDfp leaves it uninitialised until the
// first SID::reset().

extension ReSIDfpChip {
    // MARK: - resample/Resampler.h

    /// Abstraction of a resampling process. Given enough input, produces output.
    enum Resampler {
        @inline(__always)
        static func clipper(_ x: Int32, _ m: Int32) -> Int32 {
            // assert(x >= 0);
            let threshold: Int32 = 28000
            if _fastPath(x < threshold) {
                return x
            }

            let max_val = Double(m)
            let t = Double(threshold) / max_val
            let a = 1.0 - t
            let b = 1.0 / a

            var value = Double(x &- threshold) / max_val
            value = t + a * tanh(b * value)
            return residfp_int(value * max_val)
        }

        /*
         * Soft Clipping implementation, splitted for test.
         */
        @inline(__always)
        static func softClipImpl(_ x: Int32) -> Int32 {
            x < 0 ? 0 &- clipper(0 &- x, 32768) : clipper(x, 32767)
        }

        /*
         * Soft Clipping into 16 bit range [-32768,32767]
         */
        @inline(__always)
        static func softClip(_ x: Int32) -> Int16 { Int16(truncatingIfNeeded: softClipImpl(x)) }

        /// Resampler::getOutput(): `output` is the resampler's output().
        @inline(__always)
        static func getOutput(_ output: Int32, _ scaleFactor: Int32) -> Int16 {
            let out = (scaleFactor &* output) / 2
            return softClip(out)
        }
    }

    // MARK: - resample/ZeroOrderResampler.h

    /// Return sample with linear interpolation.
    ///
    /// @author Antti Lankila
    struct ZeroOrderResampler {
        /// Last sample
        var cachedSample: Int32 = 0

        /// Number of cycles per sample
        let cyclesPerSample: Int32

        var sampleOffset: Int32 = 0

        /// Calculated sample
        var outputValue: Int32 = 0

        init(_ clockFrequency: Double, _ samplingFrequency: Double) {
            cyclesPerSample = residfp_int(clockFrequency / samplingFrequency * 1024.0)
        }

        @inline(__always)
        mutating func input(_ sample: Int32) -> Bool {
            var ready = false

            if sampleOffset < 1024 {
                outputValue = cachedSample &+ ((sampleOffset &* (sample &- cachedSample)) >> 10)
                ready = true
                sampleOffset &+= cyclesPerSample
            }

            sampleOffset &-= 1024

            cachedSample = sample

            return ready
        }

        @inline(__always)
        func output() -> Int32 { outputValue }

        mutating func reset() {
            sampleOffset = 0
            cachedSample = 0
        }
    }

    // MARK: - resample/SincResampler.h / SincResampler.cpp

    /// This is the theoretically correct (and computationally intensive) audio sample generation.
    /// The samples are generated by resampling to the specified sampling frequency.
    /// The work rate is inversely proportional to the percentage of the bandwidth
    /// allocated to the filter transition band.
    ///
    /// This implementation is based on the paper "A Flexible Sampling-Rate Conversion Method",
    /// by J. O. Smith and P. Gosset, or rather on the expanded tutorial on the
    /// [Digital Audio Resampling Home Page](http://www-ccrma.stanford.edu/~jos/resample/).
    ///
    /// By building shifted FIR tables with samples according to the sampling frequency,
    /// this implementation dramatically reduces the computational effort in the
    /// filter convolutions, without any loss of accuracy.
    /// The filter convolutions are also vectorizable on current hardware.
    struct SincResampler {
        /// Size of the ring buffer, must be a power of 2
        static var RINGSIZE: Int32 { 2048 }

        /// Maximum error acceptable in I0 is 1e-6, or ~96 dB.
        static var I0E: Double { 1e-6 }

        static var BITS: Int32 { 16 }

        /// Table of the fir filter coefficients: firRES rows of firN.
        let firTable: UnsafeMutablePointer<Int16>

        var sampleIndex: Int32 = 0

        /// Filter resolution
        let firRES: Int32

        /// Filter length
        let firN: Int32

        let cyclesPerSample: Int32

        var sampleOffset: Int32 = 0

        var outputValue: Int32 = 0

        /// int sample[RINGSIZE * 2]
        let sample: UnsafeMutablePointer<Int32>

        /// Compute the 0th order modified Bessel function of the first kind.
        /// This function is originally from resample-1.5/filterkit.c by J. O. Smith.
        /// It is used to build the Kaiser window for resampling.
        ///
        /// - Parameter x: evaluate I0 at x
        /// - Returns: value of I0 at x.
        static func I0(_ x: Double) -> Double {
            var sum = 1.0
            var u = 1.0
            var n = 1.0
            let halfx = x / 2.0

            repeat {
                let temp = halfx / n
                u *= temp * temp
                sum += u
                n += 1.0
            } while u >= I0E * sum

            return sum
        }

        /// Calculate convolution with sample and sinc.
        ///
        /// - Parameters:
        ///   - a: sample buffer input
        ///   - b: sinc buffer
        ///   - bLength: length of the sinc buffer
        /// - Returns: convolved result
        @inline(__always)
        static func convolve(_ a: UnsafePointer<Int32>, _ b: UnsafePointer<Int16>, _ bLength: Int) -> Int32 {
            var out: Int32 = 0
            for i in 0 ..< bLength {
                out &+= a[i] &* Int32(b[i])
            }

            return (out &+ (1 << 14)) >> 15
        }

        @inline(__always)
        func fir(_ subcycle: Int32) -> Int32 {
            // Find the first of the nearest fir tables close to the phase
            var firTableFirst = (subcycle &* firRES) >> 10
            let firTableOffset = (subcycle &* firRES) & 0x3FF

            // Find firN most recent samples, plus one extra in case the FIR wraps.
            var sampleStart = sampleIndex &- firN &+ SincResampler.RINGSIZE &- 1

            let v1 = SincResampler.convolve(sample + Int(sampleStart), firTable + Int(firTableFirst &* firN), Int(firN))

            // Use next FIR table, wrap around to first FIR table using
            // previous sample.
            firTableFirst &+= 1
            if _slowPath(firTableFirst == firRES) {
                firTableFirst = 0
                sampleStart &+= 1
            }

            let v2 = SincResampler.convolve(sample + Int(sampleStart), firTable + Int(firTableFirst &* firN), Int(firN))

            // Linear interpolation between the sinc tables yields good
            // approximation for the exact value.
            return v1 &+ ((firTableOffset &* (v2 &- v1)) >> 10)
        }

        /// What the constructor derives from its arguments before it allocates anything.
        struct Parameters {
            var cyclesPerSample: Int32
            var firN: Int32
            var firRES: Int32
            var beta: Double
            var I0beta: Double
            var inv_cyclesPerSampleD: Double

            init(_ clockFrequency: Double, _ samplingFrequency: Double, _ highestAccurateFrequency: Double) {
                cyclesPerSample = residfp_int(clockFrequency / samplingFrequency * 1024.0)

                // 16 bits -> -96dB stopband attenuation.
                let A = -20.0 * log10(1.0 / Double(1 << SincResampler.BITS))
                // A fraction of the bandwidth is allocated to the transition band, which we double
                // because we design the filter to transition halfway at nyquist.
                let dw = (1.0 - 2.0 * highestAccurateFrequency / samplingFrequency) * Double.pi * 2.0

                // For calculation of beta and N see the reference for the kaiserord
                // function in the MATLAB Signal Processing Toolbox:
                // http://www.mathworks.com/help/signal/ref/kaiserord.html
                beta = 0.1102 * (A - 8.7)
                I0beta = SincResampler.I0(beta)
                let cyclesPerSampleD = clockFrequency / samplingFrequency
                inv_cyclesPerSampleD = samplingFrequency / clockFrequency

                // The filter order will maximally be 124 with the current constraints.
                // N >= (96.33 - 7.95)/(2 * pi * 2.285 * (maxfreq - passbandfreq) >= 123
                // The filter order is equal to the number of zero crossings, i.e.
                // it should be an even number (sinc is symmetric with respect to x = 0).
                var N = residfp_int((A - 7.95) / (2.285 * dw) + 0.5)
                N &+= N & 1

                // The filter length is equal to the filter order + 1.
                // The filter length must be an odd number (sinc is symmetric with respect to
                // x = 0).
                firN = residfp_int(Double(N) * cyclesPerSampleD) &+ 1
                firN |= 1

                // Error is bounded by err < 1.234 / L^2, so L = sqrt(1.234 / (2^-16)) = sqrt(1.234 * 2^16).
                firRES = residfp_int((((1.234 * Double(1 << SincResampler.BITS)).squareRoot()) * inv_cyclesPerSampleD).rounded(.up))

                // firN*firRES represent the total resolution of the sinc sampling. JOS
                // recommends a length of 2^BITS, but we don't quite use that good a filter.
                // The filter test program indicates that the filter performs well, though.
            }

            /// reSIDfp asserts `firN < RINGSIZE` (the sample ring buffer would overflow otherwise) and takes for
            /// granted that the output rate is below the input rate. With either broken the C++ reads outside
            /// its buffers; the chip falls back to `.decimate` instead.
            var usable: Bool {
                firN > 0 && firN < SincResampler.RINGSIZE && firRES > 0 && firRES < (1 << 20) && cyclesPerSample >= 1024
            }
        }

        /// Use a clock freqency of 985248Hz for PAL C64, 1022730Hz for NTSC C64.
        ///
        /// For resampling, the ratio between the clock frequency
        /// and the sample frequency is limited as follows:
        ///   125*clock_freq/sample_freq < 16384
        ///
        /// E.g. provided a clock frequency of ~ 1MHz, the sample frequency
        /// can not be set lower than ~ 8kHz.
        /// A lower sample frequency would make the resampling code overfill
        /// its 16k sample ring buffer.
        ///
        /// - Parameter p: what Parameters makes of clockFrequency, samplingFrequency and highestAccurateFrequency
        init(_ p: Parameters) {
            cyclesPerSample = p.cyclesPerSample
            firN = p.firN
            firRES = p.firRES

            sample = .allocate(capacity: Int(SincResampler.RINGSIZE) * 2)
            sample.initialize(repeating: 0, count: Int(SincResampler.RINGSIZE) * 2)

            // Allocate memory for FIR tables.
            firTable = .allocate(capacity: Int(firRES) * Int(firN))

            // The cutoff frequency is midway through the transition band, in effect the same as nyquist.
            let wc = Double.pi

            // Calculate the sinc tables.
            let scale = 32768.0 * wc * p.inv_cyclesPerSampleD / Double.pi

            // we're not interested in the fractional part
            // so use int division before converting to double
            let tmp = firN / 2
            let firN_2 = Double(tmp)

            for i in 0 ..< Int(firRES) {
                let jPhase = Double(i) / Double(firRES) + firN_2

                for j in 0 ..< Int(firN) {
                    let x = Double(j) - jPhase

                    let xt = x / firN_2
                    let kaiserXt = abs(xt) < 1.0 ? SincResampler.I0(p.beta * (1.0 - xt * xt).squareRoot()) / p.I0beta : 0.0

                    let wt = wc * x * p.inv_cyclesPerSampleD
                    let sincWt = abs(wt) >= 1e-8 ? sin(wt) / wt : 1.0

                    firTable[i * Int(firN) + j] = Int16(truncatingIfNeeded: residfp_int(scale * sincWt * kaiserXt))
                }
            }
        }

        /// A resampler that is never used (the chip's `.decimate` mode).
        init() {
            cyclesPerSample = 1024
            firN = 1
            firRES = 1
            sample = .allocate(capacity: 1)
            sample.initialize(to: 0)
            firTable = .allocate(capacity: 1)
            firTable.initialize(to: 0)
        }

        func deallocate() {
            sample.deallocate()
            firTable.deallocate()
        }

        var bytes: Int { Int(firRES) * Int(firN) * 2 + Int(SincResampler.RINGSIZE) * 2 * 4 }

        @inline(__always)
        mutating func input(_ input: Int32) -> Bool {
            var ready = false

            sample[Int(sampleIndex)] = input
            sample[Int(sampleIndex &+ SincResampler.RINGSIZE)] = input
            sampleIndex = (sampleIndex &+ 1) & (SincResampler.RINGSIZE &- 1)

            if sampleOffset < 1024 {
                outputValue = fir(sampleOffset)
                ready = true
                sampleOffset &+= cyclesPerSample
            }

            sampleOffset &-= 1024

            return ready
        }

        @inline(__always)
        func output() -> Int32 { outputValue }

        mutating func reset() {
            sample.update(repeating: 0, count: Int(SincResampler.RINGSIZE) * 2)
            sampleOffset = 0
        }
    }

    // MARK: - resample/TwoPassSincResampler.h

    /// Compose a more efficient SINC from chaining two other SINCs.
    struct TwoPassSincResampler {
        var s1: SincResampler
        var s2: SincResampler

        /// TwoPassSincResampler::create()'s choice of pass band and intermediate frequency.
        static func parameters(_ clockFrequency: Double, _ samplingFrequency: Double) -> (SincResampler.Parameters, SincResampler.Parameters) {
            // Set the passband frequency slightly below half sampling frequency
            //   pass_freq <= 0.9*sample_freq/2
            //
            // This constraint ensures that the FIR table is not overfilled.
            // For higher sampling frequencies we're fine with 20KHz
            let halfFreq = (samplingFrequency > 44000.0)
                ? 20000.0 : samplingFrequency * 0.45

            // Calculation according to Laurent Ganier.
            // It evaluates to about 120 kHz at typical settings.
            // Some testing around the chosen value seems to confirm that this does work.
            let intermediateFrequency = 2.0 * halfFreq
                + (2.0 * halfFreq * clockFrequency
                    * (samplingFrequency - 2.0 * halfFreq) / samplingFrequency).squareRoot()

            return (SincResampler.Parameters(clockFrequency, intermediateFrequency, halfFreq),
                    SincResampler.Parameters(intermediateFrequency, samplingFrequency, halfFreq))
        }

        init(_ p1: SincResampler.Parameters, _ p2: SincResampler.Parameters) {
            s1 = SincResampler(p1)
            s2 = SincResampler(p2)
        }

        /// Two resamplers that are never used.
        init() {
            s1 = SincResampler()
            s2 = SincResampler()
        }

        func deallocate() {
            s1.deallocate()
            s2.deallocate()
        }

        @inline(__always)
        mutating func input(_ sample: Int32) -> Bool {
            s1.input(sample) && s2.input(s1.output())
        }

        @inline(__always)
        func output() -> Int32 {
            s2.output()
        }

        mutating func reset() {
            s1.reset()
            s2.reset()
        }
    }
}
