// Copyright (C) 2026 Paul Tsochantaris
// SPDX-License-Identifier: GPL-2.0-or-later

@testable import SidayKit
import Foundation
import Testing

// Regression tests for ReSIDfpChip, the Swift port of reSIDfp. The expected values were produced by the
// C++ reSIDfp reference harness (sidfpref.cc: libsidplayfp 2.16.1's reSIDfp built with -ffp-contract=off
// and its table-building threads run one after the other), so these catch any change in the port's
// output without needing the C++ build.

private func fnv1a<S: Sequence>(_ bytes: S) -> UInt64 where S.Element == UInt8 {
    var h: UInt64 = 1_469_598_103_934_665_603
    for b in bytes { h = (h ^ UInt64(b)) &* 1_099_511_628_211 }
    return h
}

private func fnv1a(samples: [Int16]) -> UInt64 {
    fnv1a(samples.lazy.flatMap { [UInt8(truncatingIfNeeded: $0), UInt8(truncatingIfNeeded: $0 >> 8)] })
}

private enum ReSIDfpReference {
    // 806 lines, 344658 cycles. Generated by gen_unit_trace_fp.py.
    static let trace = """
    9 24 31, 2 23 245, 1 21 4, 1 22 48, 286 5 168, 1 6 240, 4 0 217, 4 1 28
    24 2 26, 7 3 9, 21 4 65, 79 12 34, 13 13 137, 10 7 195, 6 8 68, 10 9 195
    2 10 8, 2 11 65, 197 18 72, 19 18 65, 985 29 0, 96 29 0, 744 29 0, 2173 29 0
    1977 29 0, 2598 29 0, 594 29 0, 1774 29 0, 2366 29 0, 13 5 0, 14 6 240, 2 0 37
    6 1 17, 29 2 72, 2 3 2, 19 4 37, 198 11 248, 7 11 33, 830 18 64, 566 21 6
    2 22 158, 90 24 31, 2238 29 0, 1516 29 0, 97 29 0, 1162 29 0, 764 29 0, 1500 29 0
    131 5 34, 10 6 242, 21 0 197, 5 1 68, 20 2 91, 1 3 1, 30 4 65, 4 11 17
    2 11 16, 3 11 17, 298 19 168, 13 20 64, 23 14 150, 8 15 51, 23 16 24, 7 17 0
    28 18 69, 612 29 0, 362 29 0, 2386 29 0, 1064 29 0, 1044 29 0, 1841 29 0, 125 5 168
    9 6 168, 28 0 95, 0 1 34, 25 2 170, 3 3 9, 30 4 49, 116 11 136, 7 11 65
    2310 29 0, 1923 29 0, 70 29 0, 2207 29 0, 146 29 0, 202 29 0, 2091 29 0, 254 5 0
    16 6 240, 26 0 155, 1 1 8, 16 2 184, 6 3 11, 9 4 209, 127 12 168, 13 13 64
    15 7 185, 8 8 68, 18 9 165, 2 10 15, 20 11 103, 475 18 128, 151 29 0, 376 29 0
    857 29 0, 59 29 0, 2419 29 0, 1292 29 0, 309 29 0, 345 5 26, 1 6 137, 10 0 95
    5 1 34, 6 2 39, 4 3 6, 26 4 87, 206 11 16, 412 18 16, 1048 29 0, 2328 29 0
    1130 29 0, 1022 29 0, 795 29 0, 2075 29 0, 2309 29 0, 1646 29 0, 84 29 0, 281 5 26
    2 6 168, 1 0 205, 0 1 28, 30 2 250, 1 3 15, 15 4 71, 390 12 26, 7 13 64
    24 7 50, 3 8 103, 17 9 148, 9 10 3, 24 11 115, 169 19 34, 17 20 64, 16 14 52
    0 15 103, 17 16 8, 1 17 2, 21 18 65, 56 42 200, 3 44 800, 1811 29 0, 1121 29 0
    373 29 0, 1631 29 0, 473 29 0, 1280 29 0, 1373 29 0, 73 4 136, 51 4 33, 3 11 17
    3 11 16, 1 11 17, 221 18 32, 574 21 6, 3 22 96, 252 23 5, 2015 29 0, 1740 29 0
    2004 29 0, 2388 29 0, 1601 29 0, 744 29 0, 1926 29 0, 983 29 0, 1919 29 0, 895 4 16
    218 12 0, 2 13 64, 6 7 60, 6 8 103, 23 9 157, 8 10 12, 21 11 115, 387 19 9
    3 20 242, 25 14 199, 4 15 68, 5 16 71, 7 17 4, 26 18 65, 116 21 1, 4 22 137
    61 24 22, 68 29 0, 850 29 0, 456 29 0, 527 29 0, 903 29 0, 1110 29 0, 1238 29 0
    64 29 0, 27 11 64, 214 18 32, 1794 29 0, 121 29 0, 240 5 26, 18 6 242, 21 0 88
    1 1 34, 17 2 238, 9 3 14, 13 4 49, 55 11 72, 24 11 65, 90 18 72, 21 18 65
    97 21 7, 1 22 199, 111 24 159, 240 43 500, 842 29 0, 867 29 0, 136 29 0, 2115 29 0
    2460 29 0, 773 29 0, 46 29 0, 536 4 64, 197 11 136, 29 11 65, 347 18 32, 1344 29 0
    2304 29 0, 880 29 0, 814 29 0, 791 4 128, 331 12 26, 7 13 168, 10 7 139, 1 8 8
    18 9 139, 5 10 11, 24 11 65, 187 18 72, 57 18 129, 284 45 5, 745 29 0, 2581 29 0
    843 29 0, 2547 29 0, 973 29 0, 1358 29 0, 1543 29 0, 243 5 168, 5 6 242, 23 0 151
    8 1 8, 2 2 105, 5 3 12, 28 4 69, 260 11 128, 32 19 34, 28 20 64, 27 14 55
    2 15 103, 2 16 237, 0 17 8, 13 18 33, 1145 21 7, 3 22 113, 267 23 196, 508 29 0
    660 29 0, 1949 29 0, 1844 29 0, 2527 29 0, 2344 29 0, 1272 29 0, 170 4 64, 3 11 17
    4 11 16, 4 11 17, 330 19 9, 7 20 242, 22 14 30, 6 15 17, 4 16 154, 3 17 14
    5 18 71, 66 21 6, 0 22 194, 131 24 22, 264 46 3, 788 29 0, 1717 29 0, 755 29 0
    1282 29 0, 503 4 64, 277 11 32, 117 19 26, 5 20 168, 7 14 143, 3 15 8, 25 16 228
    9 17 10, 27 18 33, 1804 29 0, 2481 29 0, 143 4 64, 86 12 26, 30 13 64, 2 7 211
    8 8 28, 19 9 235, 7 10 12, 23 11 97, 464 18 16, 234 21 5, 3 22 158, 241 24 95
    124 45 1, 728 29 0, 746 29 0, 387 4 64, 248 11 16, 45 19 9, 1 20 64, 7 14 207
    2 15 28, 29 16 167, 6 17 11, 7 18 103, 1284 21 1, 0 22 47, 38 24 31, 1599 29 0
    1808 29 0, 1705 29 0, 649 29 0, 1144 29 0, 2463 29 0, 688 29 0, 2426 29 0, 258 29 0
    31 5 0, 19 6 240, 5 0 34, 7 1 17, 9 2 37, 0 3 7, 6 4 69, 1 11 17
    1 11 16, 1 11 17, 136 18 72, 14 18 33, 1308 21 2, 4 22 205, 72 23 2, 1578 29 0
    2147 29 0, 364 29 0, 1123 29 0, 338 29 0, 285 29 0, 2547 29 0, 61 29 0, 1548 29 0
    824 4 32, 222 11 128, 226 19 168, 20 20 64, 24 14 146, 0 15 51, 9 16 230, 8 17 13
    16 18 193, 1938 29 0, 781 29 0, 272 29 0, 711 29 0, 1676 29 0, 1660 29 0, 739 29 0
    721 29 0, 78 4 32, 281 12 9, 8 13 240, 1 7 40, 5 8 17, 7 9 58, 4 10 2
    23 11 129, 1488 21 6, 2 22 21, 16 23 247, 233 42 800, 3 44 200, 863 29 0, 978 29 0
    2582 29 0, 1411 29 0, 1605 29 0, 1971 29 0, 1979 29 0, 1480 29 0, 761 29 0, 350 4 128
    145 11 72, 6 11 65, 20 19 34, 16 20 242, 6 14 155, 5 15 8, 21 16 141, 8 17 11
    15 18 21, 1010 21 3, 4 22 162, 245 24 58, 1468 29 0, 275 29 0, 100 12 9, 26 13 168
    24 7 184, 3 8 68, 30 9 75, 5 10 14, 18 11 199, 178 18 72, 50 18 129, 1088 21 4
    2 22 133, 145 24 31, 2495 29 0, 2022 29 0, 2224 29 0, 882 29 0, 373 5 0, 19 6 242
    1 0 194, 9 1 68, 26 2 117, 3 3 7, 15 4 129, 127 12 34, 27 13 64, 28 7 145
    3 8 8, 27 9 144, 3 10 8, 23 11 81, 1179 21 0, 2 22 204, 147 23 243, 45 29 0
    901 29 0, 436 29 0, 2236 29 0, 1105 29 0, 2532 29 0, 727 29 0, 761 29 0, 26 5 0
    21 6 64, 17 0 42, 7 1 103, 5 2 123, 5 3 1, 19 4 49, 681 11 32, 100 33 -32768
    86 29 0, 887 29 0, 1950 29 0, 829 29 0, 1723 29 0, 621 29 0, 311 5 34, 9 6 242
    18 0 94, 3 1 34, 4 2 145, 1 3 3, 29 4 17, 96 11 248, 43 11 33, 178 18 64
    704 21 4, 1 22 192, 278 23 241, 835 29 0, 1982 29 0, 1617 29 0, 1102 29 0, 1263 29 0
    534 29 0, 770 29 0, 2021 29 0, 267 5 168, 20 6 242, 21 0 42, 3 1 103, 9 2 167
    9 3 4, 11 4 53, 147 12 9, 8 13 168, 10 7 216, 2 8 28, 29 9 136, 3 10 0
    2 11 103, 336 18 128, 1450 21 7, 1 22 14, 95 23 242, 88 33 0, 799 29 0, 2480 29 0
    1324 29 0, 603 29 0, 1555 29 0, 2278 29 0, 405 29 0, 306 5 0, 29 6 168, 11 0 141
    7 1 8, 27 2 131, 6 3 9, 27 4 33, 40 12 0, 19 13 64, 27 7 145, 2 8 51
    2 9 4, 4 10 7, 22 11 129, 173 19 9, 8 20 240, 6 14 201, 7 15 68, 15 16 235
    8 17 2, 16 18 71, 1272 21 2, 4 22 233, 116 23 0, 2146 29 0, 1713 29 0, 2162 29 0
    2398 29 0, 370 29 0, 2403 29 0, 1035 29 0, 848 29 0, 1901 29 0, 129 11 32, 302 19 168
    11 20 168, 9 14 158, 4 15 51, 18 16 121, 3 17 15, 14 18 33, 237 21 4, 0 22 6
    95 23 132, 513 29 0, 1965 29 0, 284 29 0, 2079 29 0, 1151 29 0, 2524 29 0, 3 4 17
    4 4 16, 3 4 17, 116 12 0, 30 13 64, 4 7 90, 9 8 34, 19 9 92, 2 10 2
    30 11 145, 706 18 128, 826 21 1, 1 22 84, 160 24 79, 102 29 0, 678 29 0, 1382 29 0
    618 29 0, 1118 29 0, 73 5 34, 26 6 64, 19 0 58, 8 1 103, 9 2 177, 2 3 2
    9 4 209, 188 11 248, 48 11 33, 1 18 17, 4 18 16, 1 18 17, 646 21 1, 0 22 82
    47 23 6, 998 29 0, 1589 29 0, 1788 29 0, 36 12 9, 26 13 168, 25 7 185, 2 8 68
    12 9 106, 1 10 10, 21 11 69, 55 19 0, 6 20 242, 18 14 92, 3 15 34, 23 16 116
    9 17 6, 29 18 35, 833 21 3, 3 22 128, 1270 29 0, 1732 29 0, 802 4 128, 133 12 0
    6 13 168, 20 7 35, 7 8 17, 22 9 13, 2 10 0, 13 11 147, 613 21 2, 2 22 15
    1949 29 0, 2235 29 0, 1445 29 0, 194 5 9, 2 6 137, 29 0 146, 9 1 51, 19 2 121
    8 3 10, 8 4 49, 333 12 168, 19 13 168, 4 7 147, 7 8 8, 19 9 206, 1 10 3
    17 11 113, 457 18 64, 780 21 1, 2 22 243, 220 23 244, 949 29 0, 1684 29 0, 1976 29 0
    847 29 0, 1215 29 0, 2491 29 0, 267 29 0, 106 29 0, 416 29 0, 384 5 9, 6 6 168
    10 0 94, 4 1 34, 2 2 15, 7 3 8, 11 4 135, 374 12 168, 27 13 240, 28 7 39
    9 8 17, 8 9 82, 8 10 8, 30 11 49, 4 18 17, 4 18 16, 4 18 17, 351 21 0
    3 22 145, 1935 29 0, 2227 29 0, 1070 29 0, 1317 29 0, 3 11 17, 2 11 16, 2 11 17
    121 18 72, 59 18 65, 1289 21 4, 4 22 168, 136 24 74, 1873 29 0, 557 29 0, 1330 29 0
    127 24 23, 115 24 28, 128 24 25, 126 24 29, 117 24 23, 117 24 16, 115 24 22, 128 24 29
    112 24 27, 116 24 26, 114 24 25, 120 24 20, 125 24 22, 126 24 27, 116 24 22, 129 24 18
    118 24 29, 111 24 18, 122 24 27, 126 24 26, 118 24 22, 111 24 18, 117 24 22, 121 24 28
    120 24 27, 123 24 26, 124 24 31, 126 24 26, 126 24 22, 130 24 31, 118 24 23, 111 24 17
    113 24 31, 111 24 31, 114 24 26, 126 24 23, 110 24 31, 123 24 31, 114 24 23, 130 24 21
    110 24 27, 111 24 24, 126 24 16, 112 24 28, 123 24 20, 115 24 23, 124 24 28, 113 24 19
    125 24 23, 126 24 20, 1 45 7, 128 24 18, 111 24 16, 124 24 29, 114 24 27, 112 24 20
    120 24 27, 127 24 25, 126 24 21, 119 24 19, 116 24 16, 115 24 22, 126 24 22, 126 24 16
    128 24 26, 129 24 24, 118 24 24, 122 24 30, 127 24 21, 113 24 17, 122 24 16, 112 24 22
    113 24 16, 117 24 19, 127 24 25, 110 24 25, 129 24 20, 116 24 30, 113 24 25, 119 24 30
    116 24 19, 117 24 21, 122 24 18, 120 24 27, 119 24 26, 125 24 21, 128 24 30, 113 24 20
    114 24 26, 111 24 23, 125 24 19, 129 24 24, 130 24 22, 119 24 20, 126 24 19, 130 24 16
    118 24 23, 129 24 25, 116 24 24, 114 24 22, 123 24 25, 3000 29 0
    """

    // Digests of the C++ reSIDfp reference's output for that trace at 985248 Hz, 48000 Hz:
    // (model, sampling, samples, sample digest, read-back digest)
    static let expected: [(SIDModel, ReSIDfpSampling, Int, UInt64, UInt64)] = [
        (.mos6581, .decimate, 16792, 0xE76951AFA647314D, 0xB8486F7D58BB26BD),
        (.mos6581, .resample, 16796, 0x6B4868F31D5DED22, 0xB8486F7D58BB26BD),
        (.mos8580, .decimate, 16792, 0x7D530147EF5544B1, 0x913CF8ED0B1E8275),
        (.mos8580, .resample, 16796, 0xE29B7D3947CE6687, 0x913CF8ED0B1E8275),
    ]

    // The same through libsidplayfp's own wrapper classes (sidfpref --mode lib --sids 3 --poweron 20000), at
    // libsidplayfp's PAL clock: (model, sampling, samples, sample digest, read-back digest)
    static let expectedAsLibsidplayfp: [(SIDModel, ReSIDfpSampling, Int, UInt64, UInt64)] = [
        (.mos6581, .resample, 16795, 0xDA95499E2140EFF8, 0x4B999F9F3713B8B4),
        (.mos8580, .resample, 16795, 0xB5AD263CB2A4B19C, 0x6FBA2689B8B3BBD0),
    ]

    // sidfpref --tables --model 6581: (name, bytes, FNV-1a 64)
    static let tables6581: [(String, Int, UInt64)] = [
        ("rnd", 8192, 0x90999416260193F0),
        ("fmc_scalars", 96, 0xE4A30A04AE0A1A5C),
        ("opamp_rev", 131072, 0x0A1EBBF754D13003),
        ("summer", 2621440, 0x217BA388009697C9),
        ("mixer", 3670018, 0xBE10CCEA77C15851),
        ("volume", 2097152, 0xD0AD80C6C78511C6),
        ("resonance", 2097152, 0x69B589D928916BFC),
        ("vcr_nVg", 131072, 0x549966EFCC4811F9),
        ("vcr_n_Ids_term", 524288, 0x15707275DA7C9782),
        ("voiceDC", 2048, 0x6A093CBE87F70DAD),
        ("f0_dac", 4096, 0xAD29E33AFE8C215E),
        ("envDAC", 1024, 0x6B512B2D20C06B8B),
        ("oscDAC", 16384, 0x318165217488BA1D),
        ("wftable", 32768, 0x081B29F93CE72C03),
        ("pulldown_1", 40960, 0xF8700B7810DABEEB),
        ("pulldown_2", 40960, 0x8E7DAE7394A82AC2),
        ("pulldown_3", 40960, 0x73BFF47F337A12FC),
        ("fir1", 5810, 0x9E46175132AA5247),
        ("fir2", 21922, 0xA2258D370B6DF623),
    ]
    // sidfpref --tables --model 8580: (name, bytes, FNV-1a 64)
    static let tables8580: [(String, Int, UInt64)] = [
        ("rnd", 8192, 0x90999416260193F0),
        ("fmc_scalars", 96, 0x6135C076B2724146),
        ("opamp_rev", 131072, 0x11D774CB4FBE7186),
        ("summer", 2621440, 0xF546AD6E78CF70A8),
        ("mixer", 3670018, 0x5397CCEA21C83712),
        ("volume", 2097152, 0xA7176984F46D159F),
        ("resonance", 2097152, 0x1BF548A05A43CC96),
        ("envDAC", 1024, 0x208CC2AF71AE1FF3),
        ("oscDAC", 16384, 0x342D020C6206342E),
        ("wftable", 32768, 0x081B29F93CE72C03),
        ("pulldown_1", 40960, 0xA2FF02ED60A2AFA1),
        ("pulldown_2", 40960, 0xD23E471ED4439014),
        ("pulldown_3", 40960, 0xE0821549CCCF360D),
        ("fir1", 5810, 0x9E46175132AA5247),
        ("fir2", 21922, 0xA2258D370B6DF623),
    ]

    static func parsedTrace() -> [(delta: Int, register: Int, value: Int)] {
        trace.split(whereSeparator: { $0 == "," || $0 == "\n" }).map { entry in
            let f = entry.split(separator: " ").map { Int($0)! }
            return (f[0], f[1], f[2])
        }
    }

    /// Renders the trace as the harnesses do: clock, then the write or call the line stands for, then read
    /// OSC3 and ENV3. `chunk` limits how many cycles are asked for at once.
    static func render(_ sid: inout ReSIDfpChip, chunk: Int = .max, bufferSize: Int = 512, otherSIDs: Int = 0) -> (samples: [Int16], readBack: [UInt8]) {
        var samples: [Int16] = []
        var readBack: [UInt8] = []
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: bufferSize)
        defer { buffer.deallocate() }
        for line in parsedTrace() {
            var left = line.delta
            while left > 0 {
                var cycles = min(left, chunk)
                left -= cycles
                while cycles > 0 {
                    let n = sid.clock(&cycles, into: buffer, maxSamples: bufferSize)
                    samples.append(contentsOf: UnsafeBufferPointer(start: buffer, count: n))
                }
            }
            switch line.register {
            case 33: sid.input(line.value)
            case 42: sid.setFilter6581Curve(Double(line.value) / 1000.0)
            case 43: sid.setFilter6581Range(Double(line.value) / 1000.0)
            case 44:
                sid.setFilter8580Curve(Double(line.value) / 1000.0)
                if sid.model == .mos8580 { sid.advanceDither(by: 2 * otherSIDs) }
            case 45: sid.setVoiceMuted(line.value & 3, (line.value >> 2) & 1 != 0)
            case 46: sid.setCombinedWaveforms(line.value == 2 ? .weak : line.value == 3 ? .strong : .average)
            default: sid.write(line.register, UInt8(truncatingIfNeeded: line.value))
            }
            readBack.append(sid.read(0x1B))
            readBack.append(sid.read(0x1C))
        }
        return (samples, readBack)
    }

    static func render(_ model: SIDModel, _ sampling: ReSIDfpSampling, chunk: Int = .max, bufferSize: Int = 512) -> (samples: [Int16], readBack: [UInt8]) {
        var sid = ReSIDfpChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: sampling)
        return render(&sid, chunk: chunk, bufferSize: bufferSize)
    }
}

@Test func reSIDfpMatchesReferenceOnEmbeddedTrace() {
    for (model, sampling, count, sampleDigest, readBackDigest) in ReSIDfpReference.expected {
        let (samples, readBack) = ReSIDfpReference.render(model, sampling)
        #expect(samples.count == count, "\(model) \(sampling)")
        #expect(fnv1a(samples: samples) == sampleDigest, "samples, \(model) \(sampling)")
        #expect(fnv1a(readBack) == readBackDigest, "OSC3/ENV3 read-backs, \(model) \(sampling)")
    }
}

@Test func reSIDfpOutputDoesNotDependOnHowItIsClocked() {
    // One cycle at a time never enters the loop for quiet stretches; 7 and 61 cut them at odd places; a
    // three-sample buffer fills up inside them.
    for (model, sampling, count, sampleDigest, readBackDigest) in ReSIDfpReference.expected where sampling == .resample {
        for (chunk, bufferSize) in [(1, 512), (7, 512), (61, 3), (Int.max, 3)] {
            let (samples, readBack) = ReSIDfpReference.render(model, sampling, chunk: chunk, bufferSize: bufferSize)
            #expect(samples.count == count, "\(model) \(chunk) \(bufferSize)")
            #expect(fnv1a(samples: samples) == sampleDigest, "samples, \(model) \(chunk) \(bufferSize)")
            #expect(fnv1a(readBack) == readBackDigest, "read-backs, \(model) \(chunk) \(bufferSize)")
        }
    }
}

@Test func reSIDfpMatchesLibsidplayfpsWrapper() {
    for (model, sampling, count, sampleDigest, readBackDigest) in ReSIDfpReference.expectedAsLibsidplayfp {
        // libsidplayfp gives the engine its CPU clock (PAL: 4433618.75 * 4 / 18) rounded to single precision.
        var sid = ReSIDfpChip(model: model, clockHz: Double(Float(4_433_618.75 * 4 / 18)), sampleRate: 48000, sampling: sampling)
        // A front end creates three emulations; the two that are not used draw five dither values each.
        sid.advanceDither(by: 10)
        sid.setFilterEnabled(true)
        sid.input(0) // ReSIDfp::model()
        sid.reset() // c64sid::reset()
        sid.write(0x18, 0x0F)
        // The power-on delay: clocked, output discarded.
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: 1024)
        defer { buffer.deallocate() }
        var powerOn = 20000
        while powerOn > 0 { _ = sid.clock(&powerOn, into: buffer, maxSamples: 1024) }

        let (samples, readBack) = ReSIDfpReference.render(&sid, otherSIDs: 2)
        #expect(samples.count == count, "\(model)")
        #expect(fnv1a(samples: samples) == sampleDigest, "samples, \(model)")
        #expect(fnv1a(readBack) == readBackDigest, "OSC3/ENV3 read-backs, \(model)")
    }
}

@Test func reSIDfpTablesMatchReference() {
    for (model, expected) in [(SIDModel.mos6581, ReSIDfpReference.tables6581), (.mos8580, ReSIDfpReference.tables8580)] {
        let sid = ReSIDfpChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: .resample)
        var found: [(String, Int, UInt64)] = []
        sid.withInternalTables { name, bytes, _ in
            if let bytes { found.append((name, bytes.count, fnv1a(bytes))) }
        }
        #expect(found.count == expected.count)
        for (a, b) in zip(found, expected) {
            #expect(a.0 == b.0 && a.1 == b.1 && a.2 == b.2, "\(model) table \(b.0)")
        }
    }
}

@Test func reSIDfpChipsAreIndependentAndSafeToCreateConcurrently() async {
    // reSIDfp shares its dither position between all chips of a model; here every chip has its own, so a
    // chip's output is the same whatever other chips exist or do. Chips are made on several threads at once.
    let results = await withTaskGroup(of: (Int, UInt64).self) { group in
        for i in 0 ..< 8 {
            group.addTask {
                let (model, sampling, _, _, _) = ReSIDfpReference.expected[i % ReSIDfpReference.expected.count]
                return (i, fnv1a(samples: ReSIDfpReference.render(model, sampling).samples))
            }
        }
        var digests = [Int: UInt64]()
        for await (i, digest) in group { digests[i] = digest }
        return digests
    }
    for i in 0 ..< 8 {
        #expect(results[i] == ReSIDfpReference.expected[i % ReSIDfpReference.expected.count].3, "chip \(i)")
    }
}

@Test func reSIDfpOscillatorAndEnvelopeReadBack() {
    for model in [SIDModel.mos6581, .mos8580] {
        var sid = ReSIDfpChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: .decimate)
        // Voice 3: sawtooth at FREQ $1000 (the top 12 accumulator bits step once per cycle),
        // attack 0, sustain 15. Setting and clearing the test bit zeroes the accumulator.
        sid.write(0x0F, 0x10); sid.write(0x13, 0x00); sid.write(0x14, 0xF0)
        sid.write(0x12, 0x08)
        sid.clock(1)
        sid.write(0x12, 0x21)
        var osc: [UInt8] = []
        for _ in 0 ..< 64 {
            sid.clock(64)
            osc.append(sid.read(0x1B))
        }
        // OSC3 is the top 8 bits: after 64*k cycles the accumulator is 64*k << 12, so OSC3 = 4*k
        // (the 8580 latches triangle/sawtooth a cycle late: 64*k - 1 gives 4*k - 1).
        let late: UInt8 = model == .mos8580 ? 1 : 0
        #expect(osc == (1 ... 64).map { UInt8(truncatingIfNeeded: 4 * $0) &- late }, "\(model)")
        // Attack rate 0 steps the envelope every 9 cycles: 64 * 64 cycles is enough to reach 255.
        let top = sid.read(0x1C)
        #expect(top == 0xFF, "\(model)")
        // Gate off with release 0: back to zero within 9 * 756 cycles (the exponential decay table).
        sid.write(0x12, 0x20)
        sid.clock(9 * 760)
        let bottom = sid.read(0x1C)
        #expect(bottom == 0x00, "\(model)")
    }
}

@Test func reSIDfpBusValueFades() {
    for (model, ttl) in [(SIDModel.mos6581, 0x1D00), (.mos8580, 0xA2000)] {
        var sid = ReSIDfpChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: .decimate)
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: 1024)
        defer { buffer.deallocate() }
        func run(_ sid: inout ReSIDfpChip, _ count: Int) {
            var cycles = count
            while cycles > 0 { _ = sid.clock(&cycles, into: buffer, maxSamples: 1024) }
        }
        run(&sid, 10)
        // A write-only register reads back the last value on the bus...
        sid.write(0x05, 0xA5)
        run(&sid, ttl - 1)
        let held = sid.read(0x05)
        #expect(held == 0xA5, "\(model)")
        // ...until it has faded.
        sid.write(0x05, 0xA5)
        run(&sid, ttl)
        let faded = sid.read(0x05)
        #expect(faded == 0x00, "\(model)")
        // Reading a write-only register halves the time that is left.
        sid.write(0x05, 0x5A)
        run(&sid, ttl / 2)
        let untouched = sid.read(0x1F)
        sid.write(0x05, 0x5A)
        let first = sid.read(0x1F)
        run(&sid, ttl / 2)
        let second = sid.read(0x05)
        #expect([untouched, first, second] == [0x5A, 0x5A, 0x00], "\(model)")
        // The paddle registers are not modelled and read 0xff.
        let paddles = [sid.read(0x19), sid.read(0x1A)]
        #expect(paddles == [0xFF, 0xFF])
    }
}

@Test func reSIDfpClockStopsWhenTheBufferIsFull() {
    for sampling in [ReSIDfpSampling.decimate, .resample] {
        var sid = ReSIDfpChip(model: .mos8580, clockHz: 985_248, sampleRate: 48000, sampling: sampling)
        #expect(sid.samplingMethod == sampling)
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: 64)
        defer { buffer.deallocate() }
        // One second of cycles into a 64-sample buffer: 64 samples come out and the rest stay.
        var cycles = 985_248
        let first = sid.clock(&cycles, into: buffer, maxSamples: 64)
        #expect(first == 64)
        #expect(cycles > 985_248 - 66 * 21 && cycles < 985_248 - 63 * 20)
        // Draining the rest gives a second's worth of samples. reSIDfp's resamplers step by a whole number
        // of 1024ths of a cycle, rounded down, so they run fast: 985248 * 1024 / 21018 = 48001.4 samples per
        // PAL second when decimating, and with the two passes of the sinc resampler (8334 and 2582) 48010.5.
        var total = first
        while cycles > 0 { total += sid.clock(&cycles, into: buffer, maxSamples: 64) }
        let expected = sampling == .decimate ? 48001 : 48010
        #expect(abs(total - expected) <= 1, "\(sampling): \(total)")
        // Nothing happens without room for a sample.
        var more = 100
        let none = sid.clock(&more, into: buffer, maxSamples: 0)
        #expect(none == 0 && more == 100)
    }
}

@Test func reSIDfpFallsBackToDecimationWhenResamplingCannotWork() {
    // reSIDfp's sinc resampler needs its FIR to fit a 2048-sample ring buffer (it asserts): at a PAL clock
    // that fails below about 90 Hz.
    let low = ReSIDfpChip(model: .mos6581, clockHz: 985_248, sampleRate: 40, sampling: .resample)
    #expect(low.samplingMethod == .decimate)
    for rate in [8000.0, 22050, 44100, 48000, 96000, 192_000] {
        let sid = ReSIDfpChip(model: .mos6581, clockHz: 985_248, sampleRate: rate, sampling: .resample)
        #expect(sid.samplingMethod == .resample, "\(rate)")
    }
}

@Test func reSIDfpMutingMasksControlRegisterWrites() {
    // Peak-to-peak output of a sawtooth on voice 1, after the DC step of switching the chip on has settled.
    func swing(muted: Bool) -> Int {
        var sid = ReSIDfpChip(model: .mos8580, clockHz: 985_248, sampleRate: 48000, sampling: .decimate)
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: 4096)
        defer { buffer.deallocate() }
        sid.setVoiceMuted(0, muted)
        sid.write(0x18, 0x0F)
        sid.write(0x00, 0x00); sid.write(0x01, 0x20); sid.write(0x05, 0x00); sid.write(0x06, 0xF0)
        sid.write(0x04, 0x21) // sawtooth, gate: muted, neither bit arrives
        var cycles = 400_000
        while cycles > 0 { _ = sid.clock(&cycles, into: buffer, maxSamples: 4096) }
        cycles = 20000
        var low = Int.max, high = Int.min
        while cycles > 0 {
            let n = sid.clock(&cycles, into: buffer, maxSamples: 4096)
            for i in 0 ..< n {
                low = min(low, Int(buffer[i]))
                high = max(high, Int(buffer[i]))
            }
        }
        return high - low
    }
    let audible = swing(muted: false), silent = swing(muted: true)
    #expect(audible > 4000, "\(audible)")
    #expect(silent < 200, "\(silent)")
}
