// Copyright (C) 2026 Paul Tsochantaris
// SPDX-License-Identifier: GPL-2.0-or-later

@testable import SidayKit
import Foundation
import Testing

// Regression tests for SIDChip, the Swift port of reSID. The expected values were produced by the
// C++ reSID reference harness (sidref.cc, built with -ffp-contract=off), so these catch any change
// in the port's output without needing the C++ build.

private func fnv1a<S: Sequence>(_ bytes: S) -> UInt64 where S.Element == UInt8 {
    var h: UInt64 = 1_469_598_103_934_665_603
    for b in bytes { h = (h ^ UInt64(b)) &* 1_099_511_628_211 }
    return h
}

private enum SIDReference {
    // 897 lines, 317083 cycles. Generated by gen_unit_trace.py.
    static let trace = """
    9 24 31, 2 23 101, 1 21 4, 1 22 48, 286 5 168, 1 6 240, 4 0 217, 4 1 28
    24 2 26, 7 3 9, 21 4 65, 79 12 34, 13 13 137, 10 7 195, 6 8 68, 10 9 195
    2 10 8, 2 11 65, 197 18 72, 19 18 65, 985 29 0, 96 29 0, 744 29 0, 2173 29 0
    1977 29 0, 2598 29 0, 594 29 0, 1774 29 0, 2366 29 0, 13 5 0, 14 6 240, 2 0 37
    6 1 17, 29 2 72, 2 3 2, 19 4 37, 198 11 248, 7 11 33, 830 18 64, 566 21 6
    2 22 158, 90 24 31, 2238 29 0, 1516 29 0, 97 29 0, 1162 29 0, 764 29 0, 1500 29 0
    131 5 34, 10 6 242, 21 0 197, 5 1 68, 20 2 91, 1 3 1, 30 4 65, 39 18 136
    21 18 65, 327 21 5, 4 22 101, 2014 29 0, 2252 29 0, 52 29 0, 1834 29 0, 1283 29 0
    612 29 0, 362 29 0, 2386 29 0, 141 5 34, 3 6 168, 17 0 99, 4 1 34, 28 2 29
    0 3 4, 10 4 51, 90 11 136, 22 11 33, 6 19 168, 1 20 240, 17 14 98, 6 15 34
    18 16 31, 5 17 2, 16 18 115, 1963 29 0, 297 29 0, 96 4 136, 27 4 65, 127 12 168
    13 13 64, 15 7 185, 8 8 68, 18 9 165, 2 10 15, 20 11 103, 475 18 128, 151 29 0
    376 29 0, 857 29 0, 59 29 0, 2419 29 0, 1292 29 0, 309 29 0, 345 5 26, 1 6 137
    10 0 95, 5 1 34, 6 2 39, 4 3 6, 26 4 87, 206 11 16, 412 18 16, 1048 29 0
    2328 29 0, 1130 29 0, 1022 29 0, 795 29 0, 2075 29 0, 2309 29 0, 1646 29 0, 84 29 0
    281 5 26, 2 6 168, 1 0 205, 0 1 28, 30 2 250, 1 3 15, 15 4 71, 390 12 26
    7 13 64, 24 7 50, 3 8 103, 17 9 148, 9 10 3, 24 11 115, 169 19 34, 17 20 64
    16 14 52, 0 15 103, 17 16 8, 1 17 2, 21 18 65, 1356 29 0, 1811 29 0, 1121 29 0
    169 5 34, 13 6 168, 28 0 90, 4 1 34, 9 2 199, 1 3 11, 24 4 193, 99 12 34
    22 13 64, 30 7 36, 7 8 17, 15 9 100, 7 10 10, 14 11 21, 892 18 128, 959 21 7
    0 22 117, 159 23 230, 177 29 0, 1957 29 0, 327 5 9, 5 6 242, 5 0 99, 1 1 34
    3 2 173, 8 3 4, 25 4 21, 346 12 34, 27 13 240, 17 7 44, 1 8 17, 16 9 42
    6 10 2, 30 11 145, 384 19 34, 25 20 137, 22 14 32, 0 15 17, 1 16 254, 4 17 10
    20 18 33, 1284 21 1, 4 22 124, 36 23 208, 1822 29 0, 237 29 0, 1496 29 0, 794 29 0
    296 5 26, 26 6 168, 7 0 146, 2 1 51, 14 2 176, 5 3 10, 6 4 101, 22 12 9
    27 13 168, 23 7 219, 0 8 28, 25 9 191, 8 10 14, 12 11 67, 94 19 0, 21 20 242
    10 14 154, 3 15 8, 14 16 120, 4 17 13, 20 18 69, 2530 29 0, 700 29 0, 1344 29 0
    2304 29 0, 880 29 0, 791 11 128, 331 19 26, 7 20 168, 10 14 139, 1 15 8, 18 16 139
    5 17 11, 24 18 65, 1414 29 0, 2275 29 0, 1569 29 0, 745 29 0, 203 4 32, 387 12 168
    16 13 242, 5 7 205, 9 8 28, 2 9 105, 5 10 12, 28 11 81, 260 18 128, 219 21 1
    2 22 223, 34 24 70, 1182 29 0, 262 29 0, 239 29 0, 1607 29 0, 140 5 34, 26 6 137
    4 0 46, 2 1 17, 15 2 235, 9 3 14, 19 4 101, 106 12 34, 15 13 242, 16 7 34
    6 8 17, 20 9 222, 0 10 7, 22 11 193, 166 18 72, 16 18 129, 425 29 0, 820 29 0
    613 29 0, 1771 29 0, 1598 29 0, 133 29 0, 367 29 0, 1049 29 0, 96 29 0, 101 4 248
    14 4 33, 162 12 26, 9 13 168, 9 7 220, 1 8 28, 3 9 38, 1 10 5, 8 11 151
    425 21 0, 1 22 100, 179 23 22, 602 29 0, 1262 29 0, 1164 29 0, 916 29 0, 1160 29 0
    823 29 0, 1849 29 0, 993 29 0, 416 11 16, 1460 21 6, 0 22 250, 235 24 22, 1309 29 0
    469 29 0, 15 12 9, 6 13 242, 11 7 147, 6 8 51, 21 9 167, 4 10 8, 29 11 193
    249 19 0, 6 20 240, 13 14 216, 3 15 28, 26 16 164, 5 17 5, 29 18 193, 1815 29 0
    1975 29 0, 417 29 0, 2568 29 0, 71 29 0, 78 4 32, 399 12 9, 9 13 242, 6 7 196
    9 8 68, 8 9 181, 5 10 1, 5 11 87, 156 21 1, 4 22 28, 58 23 71, 1108 29 0
    80 29 0, 712 29 0, 658 29 0, 95 29 0, 91 12 9, 6 13 64, 25 7 144, 8 8 8
    19 9 53, 9 10 4, 30 11 113, 677 18 128, 561 21 4, 0 22 40, 35 24 159, 2431 29 0
    989 29 0, 1665 29 0, 916 29 0, 1906 29 0, 1206 29 0, 91 29 0, 93 4 64, 225 12 34
    17 13 64, 26 7 157, 6 8 51, 15 9 192, 2 10 13, 2 11 17, 105 18 136, 13 18 33
    810 29 0, 984 29 0, 1858 29 0, 125 5 0, 1 6 137, 3 0 211, 3 1 28, 23 2 122
    3 3 8, 29 4 113, 237 19 26, 28 20 242, 15 14 205, 3 15 28, 20 16 84, 5 17 7
    30 18 193, 989 21 3, 2 22 241, 95 24 159, 1624 29 0, 219 29 0, 2321 29 0, 926 29 0
    265 29 0, 1713 29 0, 969 29 0, 20 5 34, 16 6 242, 6 0 200, 5 1 68, 21 2 141
    8 3 11, 15 4 21, 225 12 168, 10 13 240, 25 7 220, 5 8 28, 11 9 215, 2 10 1
    8 11 35, 308 21 1, 1 22 97, 106 23 229, 2409 29 0, 1723 29 0, 136 4 136, 20 4 33
    38 12 26, 21 13 137, 10 7 44, 2 8 17, 19 9 196, 8 10 2, 1 11 113, 803 18 32
    514 21 4, 3 22 14, 58 24 42, 973 29 0, 1136 29 0, 1060 29 0, 697 29 0, 1672 29 0
    2358 29 0, 1396 29 0, 1179 29 0, 11 11 72, 55 11 129, 901 29 0, 436 29 0, 232 12 0
    12 13 240, 2 7 47, 0 8 103, 17 9 130, 7 10 13, 21 11 193, 342 19 168, 29 20 168
    24 14 223, 2 15 28, 1 16 65, 3 17 8, 25 18 69, 1723 29 0, 621 29 0, 2107 29 0
    2406 29 0, 2047 29 0, 280 5 9, 4 6 240, 22 0 148, 1 1 8, 29 2 6, 5 3 8
    19 4 133, 245 11 32, 92 19 168, 5 20 240, 18 14 45, 6 15 17, 26 16 54, 7 17 6
    13 18 81, 534 29 0, 770 29 0, 2021 29 0, 1732 29 0, 2293 29 0, 117 29 0, 130 12 9
    9 13 242, 11 7 161, 4 8 51, 9 9 129, 5 10 3, 16 11 71, 75 18 248, 54 18 33
    364 21 6, 0 22 151, 127 23 21, 55 29 0, 2437 29 0, 159 29 0, 642 29 0, 766 29 0
    100 29 0, 787 29 0, 706 29 0, 1440 29 0, 890 4 64, 282 12 26, 2 13 240, 19 7 222
    3 8 28, 29 9 187, 2 10 3, 11 11 145, 186 21 0, 4 22 214, 30 23 145, 319 29 0
    2396 29 0, 1577 29 0, 59 4 72, 51 4 129, 102 12 34, 5 13 168, 4 7 143, 2 8 8
    3 9 207, 7 10 14, 17 11 69, 361 19 9, 20 20 240, 16 14 158, 8 15 51, 17 16 18
    9 17 13, 3 18 37, 950 21 0, 2 22 101, 698 29 0, 847 29 0, 136 29 0, 470 4 16
    9 11 248, 35 11 65, 283 18 64, 893 21 5, 2 22 105, 79 24 95, 303 29 0, 762 29 0
    1608 29 0, 141 5 168, 29 6 137, 15 0 153, 4 1 8, 1 2 69, 7 3 1, 24 4 19
    395 12 26, 4 13 242, 17 7 145, 1 8 8, 30 9 6, 9 10 4, 28 11 39, 467 18 64
    1464 21 2, 2 22 67, 133 23 83, 678 29 0, 1382 29 0, 188 5 26, 19 6 242, 29 0 154
    1 1 8, 23 2 3, 2 3 8, 9 4 129, 188 11 248, 48 11 33, 113 21 4, 1 22 249
    87 23 144, 2090 29 0, 1787 29 0, 2286 29 0, 41 5 26, 16 6 240, 6 0 41, 9 1 17
    22 2 27, 2 3 2, 26 4 19, 377 12 34, 12 13 240, 21 7 47, 2 8 103, 6 9 51
    1 10 15, 16 11 149, 106 19 168, 29 20 242, 17 14 47, 4 15 17, 14 16 180, 0 17 12
    10 18 113, 66 21 1, 1 22 246, 106 24 38, 387 29 0, 766 29 0, 708 29 0, 2500 29 0
    1951 29 0, 2461 29 0, 163 18 128, 162 29 0, 1226 29 0, 1358 29 0, 298 29 0, 1949 29 0
    2235 29 0, 194 5 9, 2 6 137, 29 0 185, 9 1 68, 19 2 121, 8 3 10, 8 4 49
    333 12 168, 19 13 168, 4 7 147, 7 8 8, 19 9 206, 1 10 3, 17 11 113, 457 18 64
    780 21 1, 2 22 243, 220 23 100, 949 29 0, 1684 29 0, 1976 29 0, 847 29 0, 1215 29 0
    2491 29 0, 267 29 0, 106 29 0, 416 29 0, 384 5 9, 6 6 168, 10 0 94, 4 1 34
    2 2 15, 7 3 8, 11 4 135, 374 12 168, 27 13 240, 28 7 39, 9 8 17, 8 9 82
    8 10 8, 30 11 49, 891 21 1, 4 22 235, 186 24 79, 597 29 0, 1935 29 0, 2227 29 0
    1070 29 0, 1317 29 0, 2206 29 0, 154 29 0, 1322 29 0, 211 5 0, 22 6 137, 25 0 43
    9 1 17, 10 2 52, 4 3 8, 19 4 65, 665 21 5, 4 22 64, 269 24 95, 2509 29 0
    1603 29 0, 2379 29 0, 1259 29 0, 117 5 168, 21 6 240, 6 0 94, 3 1 34, 28 2 29
    1 3 13, 25 4 17, 178 12 168, 5 13 64, 7 7 209, 8 8 28, 29 9 178, 3 10 11
    7 11 33, 269 18 128, 1700 29 0, 1448 29 0, 2183 29 0, 128 5 168, 7 6 137, 13 0 30
    5 1 17, 14 2 36, 5 3 11, 15 4 17, 363 12 168, 24 13 64, 23 7 221, 4 8 28
    2 9 54, 0 10 7, 4 11 71, 263 19 9, 1 20 64, 14 14 91, 7 15 34, 8 16 183
    2 17 4, 1 18 65, 1067 21 0, 0 22 138, 42 24 54, 762 29 0, 953 29 0, 1870 29 0
    1580 29 0, 68 5 168, 22 6 240, 2 0 57, 0 1 103, 14 2 177, 2 3 14, 17 4 69
    339 12 168, 18 13 242, 21 7 142, 4 8 8, 25 9 62, 4 10 5, 4 11 49, 267 19 0
    19 20 137, 20 14 35, 4 15 17, 9 16 247, 6 17 8, 15 18 113, 1445 21 0, 0 22 63
    88 29 0, 330 29 0, 2269 29 0, 912 29 0, 538 29 0, 127 29 0, 973 29 0, 458 29 0
    75 5 9, 15 6 240, 28 0 147, 4 1 8, 19 2 136, 7 3 9, 7 4 149, 230 11 32
    177 19 26, 21 20 168, 19 14 216, 7 15 28, 25 16 161, 2 17 3, 24 18 145, 473 21 7
    3 22 19, 57 23 131, 2531 29 0, 596 29 0, 2155 29 0, 545 29 0, 70 29 0, 1107 29 0
    117 24 25, 116 24 24, 114 24 22, 123 24 25, 122 24 28, 113 24 23, 121 24 28, 123 24 29
    125 24 19, 119 24 18, 127 24 20, 121 24 22, 110 24 25, 130 24 20, 129 24 19, 125 24 22
    120 24 25, 110 24 26, 128 24 17, 125 24 29, 130 24 20, 125 24 27, 111 24 17, 126 24 26
    118 24 24, 129 24 25, 116 24 27, 126 24 17, 111 24 29, 127 24 22, 130 24 20, 112 24 30
    127 24 17, 114 24 19, 118 24 16, 123 24 28, 116 24 30, 114 24 31, 130 24 23, 113 24 31
    112 24 20, 115 24 21, 112 24 27, 111 24 24, 124 24 30, 120 24 23, 122 24 31, 111 24 18
    124 24 27, 122 24 22, 110 24 20, 128 24 29, 115 24 16, 129 24 24, 115 24 23, 130 24 30
    119 24 19, 124 24 17, 127 24 28, 112 24 23, 117 24 29, 123 24 30, 117 24 29, 111 24 17
    126 24 16, 117 24 25, 116 24 27, 126 24 30, 115 24 20, 111 24 16, 126 24 18, 122 24 28
    117 24 17, 112 24 20, 112 24 25, 120 24 23, 113 24 21, 124 24 21, 111 24 19, 129 24 28
    110 24 25, 124 24 20, 128 24 31, 112 24 28, 123 24 18, 123 24 18, 123 24 30, 130 24 26
    129 24 29, 126 24 30, 115 24 29, 116 24 24, 126 24 16, 128 24 21, 110 24 17, 119 24 27
    120 24 16, 116 24 24, 127 24 20, 113 24 26, 111 24 23, 122 24 22, 111 24 19, 128 24 24
    124 24 23, 130 24 27, 123 24 27, 117 24 31, 116 24 22, 122 24 20, 124 24 20, 115 24 23
    129 24 24, 128 24 24, 115 24 30, 116 24 30, 123 24 23, 120 24 21, 119 24 23, 112 24 19
    3000 29 0
    """

    // Digests of the C++ reSID reference's output for that trace at 985248 Hz, 48000 Hz:
    // (model, sampling, samples, sample digest, read-back digest)
    static let expected: [(SIDModel, SIDSampling, Int, UInt64, UInt64)] = [
        (.mos6581, .fast, 15447, 0x9F8B592239B4742E, 0x691B9761EA69E984),
        (.mos6581, .interpolate, 15447, 0x812C940CE564E97E, 0x97D7E2A219C39F9D),
        (.mos6581, .resample, 15447, 0x7847456F1111C87F, 0x97D7E2A219C39F9D),
        (.mos6581, .resampleFastMem, 15447, 0xEA7260CF919B769C, 0x97D7E2A219C39F9D),
        (.mos8580, .fast, 15447, 0xACBB56C147EAF2EA, 0x03334CF6D1A92CFB),
        (.mos8580, .interpolate, 15447, 0x1A9B3F16FC8BD97B, 0x4C48DD2E091EAF6B),
        (.mos8580, .resample, 15447, 0xF64E8E9DF3C3C6F9, 0x4C48DD2E091EAF6B),
        (.mos8580, .resampleFastMem, 15447, 0x08335D8C983A9C79, 0x4C48DD2E091EAF6B),
    ]
    // FNV-1a digests of reSID's lookup tables as the C++ builds them (name, bytes, digest), in the
    // order SIDChip.withInternalTables presents them; .resample at 985248 Hz / 48000 Hz for "fir".
    static let tables6581: [(String, Int, UInt64)] = [
        ("scalars", 64, 0x45BD47651493A087),
        ("vo_N16", 8, 0x909F70281816D57E),
        ("opamp_rev", 131072, 0x031E49205ED0B168),
        ("summer", 2621440, 0x527DD0393FCD6EB0),
        ("gain", 2097152, 0xD30F90C5D3609C28),
        ("resonance", 2097152, 0x23689286B5391B47),
        ("mixer", 3670018, 0xDF1568368C814F27),
        ("f0_dac", 4096, 0x660BECE1F25AE101),
        ("vcr_kVg", 131072, 0x549966EFCC4811F9),
        ("vcr_n_Ids_term", 131072, 0xBE15E9DFBDE3448A),
        ("rnd", 4096, 0x40F60ACB11E9A6DE),
        ("model_wave", 65536, 0x858D0A8EC61CB528),
        ("wave_dac", 8192, 0x238FBB1B75F5EC6F),
        ("env_dac", 512, 0x84C6B2B82A291164),
        ("fir", 24992, 0x5A61592E97A16B38),
    ]

    static let tables8580: [(String, Int, UInt64)] = [
        ("scalars", 64, 0x05578D2C5713C437),
        ("vo_N16", 8, 0xED4BB4BB66D97CAD),
        ("opamp_rev", 131072, 0x24FE0519BB992452),
        ("summer", 2621440, 0xFBBCF359C3E04FA3),
        ("gain", 2097152, 0xB2BCBD55554E6CFF),
        ("resonance", 2097152, 0x05D3764302510F6D),
        ("mixer", 3670018, 0x1E250923481ED172),
        ("f0_dac", 4096, 0xBF0A91C4FB39F99B),
        ("rnd", 4096, 0x40F60ACB11E9A6DE),
        ("model_wave", 65536, 0xB284649D15C70153),
        ("wave_dac", 8192, 0x5B6677631F9C08D7),
        ("env_dac", 512, 0xCCD0F76D441066D2),
        ("fir", 24992, 0x5A61592E97A16B38),
    ]

    static func parsedTrace() -> [(delta: Int, register: Int, value: UInt8)] {
        trace.split(whereSeparator: { $0 == "," || $0 == "\n" }).map { entry in
            let f = entry.split(separator: " ").map { Int($0)! }
            return (f[0], f[1], UInt8(f[2]))
        }
    }

    /// Renders the trace as the harnesses do: clock, write, then read OSC3 and ENV3.
    static func render(_ model: SIDModel, _ sampling: SIDSampling) -> (samples: [Int16], readBack: [UInt8]) {
        var sid = SIDChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: sampling)
        defer { sid.deallocate() }
        var samples: [Int16] = []
        var readBack: [UInt8] = []
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: 512)
        defer { buffer.deallocate() }
        for line in parsedTrace() {
            var cycles = line.delta
            while cycles > 0 {
                let n = sid.clock(&cycles, into: buffer, maxSamples: 512)
                samples.append(contentsOf: UnsafeBufferPointer(start: buffer, count: n))
            }
            sid.write(line.register, line.value)
            readBack.append(sid.read(0x1B))
            readBack.append(sid.read(0x1C))
        }
        return (samples, readBack)
    }
}

@Test func sidMatchesReSIDOnEmbeddedTrace() {
    for (model, sampling, count, sampleDigest, readBackDigest) in SIDReference.expected {
        let (samples, readBack) = SIDReference.render(model, sampling)
        #expect(samples.count == count, "\(model) \(sampling)")
        let digest = fnv1a(samples.lazy.flatMap { [UInt8(truncatingIfNeeded: $0), UInt8(truncatingIfNeeded: $0 >> 8)] })
        #expect(digest == sampleDigest, "samples, \(model) \(sampling)")
        #expect(fnv1a(readBack) == readBackDigest, "OSC3/ENV3 read-backs, \(model) \(sampling)")
    }
}

@Test func sidTablesMatchReSID() {
    for (model, expected) in [(SIDModel.mos6581, SIDReference.tables6581), (.mos8580, SIDReference.tables8580)] {
        let sid = SIDChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: .resample)
        defer { sid.deallocate() }
        var found: [(String, Int, UInt64)] = []
        sid.withInternalTables { name, bytes in found.append((name, bytes.count, fnv1a(bytes))) }
        #expect(found.count == expected.count)
        for (a, b) in zip(found, expected) {
            #expect(a.0 == b.0 && a.1 == b.1 && a.2 == b.2, "\(model) table \(b.0)")
        }
    }
}

@Test func sidOscillatorAndEnvelopeReadBack() {
    for model in [SIDModel.mos6581, .mos8580] {
        var sid = SIDChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: .interpolate)
        defer { sid.deallocate() }
        // Voice 3: sawtooth at FREQ $1000 (the top 12 accumulator bits step once per cycle),
        // attack 0, sustain 15. Setting and clearing the test bit zeroes the accumulator.
        sid.write(0x0F, 0x10); sid.write(0x13, 0x00); sid.write(0x14, 0xF0)
        sid.write(0x12, 0x08)
        sid.clock()
        sid.write(0x12, 0x21)
        var osc: [UInt8] = []
        for _ in 0 ..< 64 {
            for _ in 0 ..< 64 { sid.clock() }
            osc.append(sid.read(0x1B))
        }
        // OSC3 is the top 8 bits: after 64*k cycles the accumulator is 64*k << 12, so OSC3 = 4*k
        // (the 8580 latches triangle/sawtooth a cycle late: 64*k - 1 gives 4*k - 1).
        let late: UInt8 = model == .mos8580 ? 1 : 0
        #expect(osc == (1 ... 64).map { UInt8(truncatingIfNeeded: 4 * $0) &- late }, "\(model)")
        // Attack rate 0 steps the envelope every 9 cycles: 64 * 64 cycles is enough to reach 255.
        let top = sid.read(0x1C)
        #expect(top == 0xFF, "\(model)")
        // Gate off with release 0: back to zero within 9 * 756 cycles (the exponential decay table).
        sid.write(0x12, 0x20)
        for _ in 0 ..< 9 * 760 { sid.clock() }
        let bottom = sid.read(0x1C)
        #expect(bottom == 0x00, "\(model)")
    }
}

@Test func sidBusValueFades() {
    for (model, ttl) in [(SIDModel.mos6581, 0x1D00), (.mos8580, 0xA2000)] {
        var sid = SIDChip(model: model, clockHz: 985_248, sampleRate: 48000, sampling: .interpolate)
        defer { sid.deallocate() }
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: 1024)
        defer { buffer.deallocate() }
        func run(_ sid: inout SIDChip, _ count: Int) {
            var cycles = count
            while cycles > 0 { _ = sid.clock(&cycles, into: buffer, maxSamples: 1024) }
        }
        run(&sid, 10)
        sid.write(0x05, 0xA5)
        // A write-only register reads back the last value on the bus...
        let fresh = [sid.read(0x05), sid.read(0x00), sid.read(0x1F)]
        #expect(fresh == [0xA5, 0xA5, 0xA5])
        run(&sid, ttl - 1)
        let late = sid.read(0x05)
        #expect(late == 0xA5, "\(model)")
        // ...until it has faded.
        run(&sid, 1)
        let faded = sid.read(0x05)
        #expect(faded == 0x00, "\(model)")
        // The paddle registers are not modelled and read 0xff.
        let paddles = [sid.read(0x19), sid.read(0x1A)]
        #expect(paddles == [0xFF, 0xFF])
    }
}

@Test func sidClockStopsWhenTheBufferIsFull() {
    for sampling in [SIDSampling.fast, .interpolate, .resample, .resampleFastMem] {
        var sid = SIDChip(model: .mos8580, clockHz: 985_248, sampleRate: 48000, sampling: sampling)
        defer { sid.deallocate() }
        #expect(sid.samplingMethod == sampling)
        let buffer = UnsafeMutablePointer<Int16>.allocate(capacity: 64)
        defer { buffer.deallocate() }
        // One second of cycles into a 64-sample buffer: 64 samples come out and the rest stay.
        var cycles = 985_248
        let first = sid.clock(&cycles, into: buffer, maxSamples: 64)
        #expect(first == 64)
        #expect(cycles > 985_248 - 65 * 21 && cycles < 985_248 - 64 * 20)
        // Draining the rest gives 48000 samples in all, give or take the one in progress.
        var total = first
        while cycles > 0 { total += sid.clock(&cycles, into: buffer, maxSamples: 64) }
        #expect(total == 48000 || total == 47999, "\(sampling): \(total)")
    }
}

@Test func sidFallsBackToInterpolationWhenResamplingCannotWork() {
    // reSID refuses to resample when 125 * clock / rate would overfill its 16384-sample ring buffer.
    var sid = SIDChip(model: .mos6581, clockHz: 985_248, sampleRate: 4000, sampling: .resample)
    defer { sid.deallocate() }
    #expect(sid.samplingMethod == .interpolate)
    let passbandTooWide = sid.setSamplingParameters(clockHz: 985_248, sampling: .resample, sampleRate: 48000, passFrequency: 23000)
    #expect(!passbandTooWide)
    let accepted = sid.setSamplingParameters(clockHz: 985_248, sampling: .resample, sampleRate: 48000)
    #expect(accepted)
    #expect(sid.samplingMethod == .resample)
}
